# Generated by Django 3.2.8 on 2021-10-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumgroup',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='forumgroup',
            name='sign',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
