# Generated by Django 3.2.8 on 2021-10-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20211022_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumgroup',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
