# Generated by Django 3.2.8 on 2021-10-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_forumgroup_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumgroup',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
