# Generated by Django 3.2.8 on 2021-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumgroup_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumgroup',
            name='permissions',
            field=models.CharField(choices=[('Create branches', 'CREATE_BRANCH'), ('Create categories', 'CREATE_CATEGORY'), ('Create topics', 'CREATE_TOPIC')], default='CREATE_TOPIC', max_length=50),
            preserve_default=False,
        ),
    ]
