# Generated by Django 3.2.8 on 2021-10-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_forumgroup_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumgroup',
            name='permissions',
            field=models.CharField(choices=[('CREATE_BRANCH', 'Create branches'), ('CREATE_CATEGORY', 'Create categories'), ('CREATE_TOPIC', 'Create topics')], max_length=300),
        ),
    ]
