# Generated by Django 3.2.8 on 2021-10-24 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_branch_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='forum.branch'),
        ),
    ]
