# Generated by Django 3.2.8 on 2021-10-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_alter_category_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
