# Generated by Django 3.2.8 on 2021-10-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_post_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
