# Generated by Django 3.2.8 on 2021-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0024_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='./profile_pictures/default.jpg', null=True, upload_to='./profile_pictures'),
        ),
    ]
